### ISSUE TITLE
can't run the example

### ISSUE THREAD

**Issue by smallnest** [spance/go-callprivate#1]
I have run the example but it can't work:

```
panic: reflect: call of reflect.Value.Call on zero Value

goroutine 1 [running]:
reflect.flag.mustBe(0x0, 0x13)
        C:/Go/src/reflect/value.go:201 +0xb5
reflect.Value.Call(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/reflect/value.go:300 +0x3f
main.main()
        C:/chaos/go/src/github.com/smallnest/private/main.go:23 +0x10c
exit status 2
```

**Comment by spance** [comment]
Hi, I have test it on the newest golang 1.8.1 and it failed.
This experiential library was developed on golang 1.6.x, and it was just for learning and testing.
I'm sorry that I don't have more time to continue to develop this project, so this project will be suspended.

**Comment by smallnest** [comment]
OK, thanks
